// AUTO-GENERATED by scripts/build-quiz-data.mjs — do not hand edit.
// Do not commit the source pool file this was built from.

export interface QuizSources {
  talk?: string;
  site?: string;
  docs?: string;
  repos?: string[];
}

// Where the question pool's facts come from. No answer content — safe to ship as-is.
export const quizSources: QuizSources = {
  "talk": "https://www.youtube.com/watch?v=64WEB4S78nQ",
  "site": "https://cuga.dev",
  "docs": "https://docs.cuga.dev",
  "repos": [
    "https://github.com/cuga-project/cuga-agent",
    "https://github.com/cuga-project/cuga-apps",
    "https://github.com/cuga-project/cuga-skills",
    "https://github.com/cuga-project/cuga-harness-kit"
  ]
};
