// AUTO-GENERATED by scripts/build-quiz-data.mjs — do not hand edit.
// Do not commit the source pool file this was built from.

import type { QuizQuestion } from "../lib/quizTypes";

export const quizPool: QuizQuestion[] = [
  {
    "id": "q1",
    "difficulty": "easy",
    "question": "What does CUGA stand for?",
    "options": [
      {
        "id": "a",
        "text": "ConfigUrable Generalist Agent"
      },
      {
        "id": "b",
        "text": "Cognitive Unified Graph Agent"
      },
      {
        "id": "c",
        "text": "Composable Universal Gateway Agent"
      },
      {
        "id": "d",
        "text": "Cloud Unified Governance Architecture"
      }
    ]
  },
  {
    "id": "q2",
    "difficulty": "easy",
    "question": "Which organization created and open-sourced CUGA?",
    "options": [
      {
        "id": "a",
        "text": "Hugging Face"
      },
      {
        "id": "b",
        "text": "IBM Research"
      },
      {
        "id": "c",
        "text": "LangChain Inc."
      },
      {
        "id": "d",
        "text": "The Linux Foundation"
      }
    ]
  },
  {
    "id": "q3",
    "difficulty": "easy",
    "question": "How does cuga.dev position CUGA?",
    "options": [
      {
        "id": "a",
        "text": "A foundation model fine-tuned for tool use"
      },
      {
        "id": "b",
        "text": "A low-code chatbot builder"
      },
      {
        "id": "c",
        "text": "An agent harness for the enterprise"
      },
      {
        "id": "d",
        "text": "A vector database for agent memory"
      }
    ]
  },
  {
    "id": "q4",
    "difficulty": "easy",
    "question": "In the talk, what does calling CUGA an 'agent harness' mean?",
    "options": [
      {
        "id": "a",
        "text": "It is a testing rig for benchmarking LLMs"
      },
      {
        "id": "b",
        "text": "It takes care of LLM calls, policies, tools, memory, knowledge, and secure execution so developers focus on business logic and tools"
      },
      {
        "id": "c",
        "text": "It is a wrapper that converts LangGraph graphs into REST APIs"
      },
      {
        "id": "d",
        "text": "It is a hardware accelerator for agent inference"
      }
    ]
  },
  {
    "id": "q5",
    "difficulty": "easy",
    "question": "The AppWorld benchmark, on which CUGA held the #1 spot, consists of:",
    "options": [
      {
        "id": "a",
        "text": "100 web navigation tasks across 5 sites"
      },
      {
        "id": "b",
        "text": "750 real-world tasks across 457 APIs"
      },
      {
        "id": "c",
        "text": "10,000 coding problems"
      },
      {
        "id": "d",
        "text": "Multiple-choice questions about enterprise software"
      }
    ]
  },
  {
    "id": "q6",
    "difficulty": "easy",
    "question": "What does the WebArena benchmark primarily evaluate?",
    "options": [
      {
        "id": "a",
        "text": "Code generation quality"
      },
      {
        "id": "b",
        "text": "Autonomous web agents completing tasks across application domains"
      },
      {
        "id": "c",
        "text": "Retrieval accuracy over PDFs"
      },
      {
        "id": "d",
        "text": "LLM inference latency"
      }
    ]
  },
  {
    "id": "q7",
    "difficulty": "easy",
    "question": "Through which routes can you define CUGA policies such as Intent Guards and Playbooks?",
    "options": [
      {
        "id": "a",
        "text": "Only by editing settings.toml"
      },
      {
        "id": "b",
        "text": "Through the Python SDK or the CUGA web UI"
      },
      {
        "id": "c",
        "text": "Only through a REST admin API"
      },
      {
        "id": "d",
        "text": "Only by fine-tuning the model"
      }
    ]
  },
  {
    "id": "q8",
    "difficulty": "easy",
    "question": "Which three tool integration types does CUGA support natively?",
    "options": [
      {
        "id": "a",
        "text": "GraphQL, gRPC, SOAP"
      },
      {
        "id": "b",
        "text": "OpenAPI specs, MCP servers, and LangChain tools"
      },
      {
        "id": "c",
        "text": "Zapier, IFTTT, Webhooks only"
      },
      {
        "id": "d",
        "text": "SQL, Bash, and Excel macros"
      }
    ]
  },
  {
    "id": "q9",
    "difficulty": "easy",
    "question": "Where can you try CUGA live in a browser without installing it?",
    "options": [
      {
        "id": "a",
        "text": "Only through an IBM Cloud account"
      },
      {
        "id": "b",
        "text": "On Hugging Face Spaces, which hosts both the core agent and the cuga-apps gallery"
      },
      {
        "id": "c",
        "text": "Through a Chrome Web Store app"
      },
      {
        "id": "d",
        "text": "There is no hosted demo; you must install it locally"
      }
    ]
  },
  {
    "id": "q10",
    "difficulty": "easy",
    "question": "Which command launches the web dashboard for visualizing agent execution trajectories?",
    "options": [
      {
        "id": "a",
        "text": "cuga trace"
      },
      {
        "id": "b",
        "text": "cuga viz"
      },
      {
        "id": "c",
        "text": "cuga logs --ui"
      },
      {
        "id": "d",
        "text": "cuga start dashboard"
      }
    ]
  },
  {
    "id": "q11",
    "difficulty": "easy",
    "question": "How many policy types does CUGA's policy system provide?",
    "options": [
      {
        "id": "a",
        "text": "3"
      },
      {
        "id": "b",
        "text": "4"
      },
      {
        "id": "c",
        "text": "5"
      },
      {
        "id": "d",
        "text": "7"
      }
    ]
  },
  {
    "id": "q12",
    "difficulty": "medium",
    "question": "Which of these is NOT one of CUGA's policy types?",
    "options": [
      {
        "id": "a",
        "text": "Intent Guard"
      },
      {
        "id": "b",
        "text": "Playbook"
      },
      {
        "id": "c",
        "text": "Rate Limiter"
      },
      {
        "id": "d",
        "text": "Output Formatter"
      }
    ]
  },
  {
    "id": "q13",
    "difficulty": "medium",
    "question": "Which policy type implements a human-in-the-loop gate before a high-risk tool is executed?",
    "options": [
      {
        "id": "a",
        "text": "Tool Guide"
      },
      {
        "id": "b",
        "text": "Tool Approval"
      },
      {
        "id": "c",
        "text": "Intent Guard"
      },
      {
        "id": "d",
        "text": "Playbook"
      }
    ]
  },
  {
    "id": "q14",
    "difficulty": "medium",
    "question": "In the healthcare claims demo, why was an Output Formatter policy added?",
    "options": [
      {
        "id": "a",
        "text": "To translate answers into another language"
      },
      {
        "id": "b",
        "text": "The agent answered other agents rather than people, so responses were formatted as JSON instead of natural language"
      },
      {
        "id": "c",
        "text": "To hide sensitive claim codes from the user"
      },
      {
        "id": "d",
        "text": "To shorten answers to fit a token budget"
      }
    ]
  },
  {
    "id": "q15",
    "difficulty": "medium",
    "question": "In the SDK, `agent.policies.add_intent_guard(..., keywords=[\"delete\",\"remove\"], response=\"...\")` will:",
    "options": [
      {
        "id": "a",
        "text": "Rewrite the user's message to remove those words"
      },
      {
        "id": "b",
        "text": "Block matching intents and return the configured response"
      },
      {
        "id": "c",
        "text": "Require human approval for any tool containing those words"
      },
      {
        "id": "d",
        "text": "Format the final answer to exclude those words"
      }
    ]
  },
  {
    "id": "q16",
    "difficulty": "medium",
    "question": "A Playbook policy is best described as:",
    "options": [
      {
        "id": "a",
        "text": "A retry policy for failed tools"
      },
      {
        "id": "b",
        "text": "A standard operating procedure (step-by-step guidance) injected when its trigger matches"
      },
      {
        "id": "c",
        "text": "A list of forbidden APIs"
      },
      {
        "id": "d",
        "text": "A deployment manifest for Kubernetes"
      }
    ]
  },
  {
    "id": "q17",
    "difficulty": "medium",
    "question": "What is required to run CUGA in 'hybrid' task mode?",
    "options": [
      {
        "id": "a",
        "text": "A GPU and CUDA drivers"
      },
      {
        "id": "b",
        "text": "Playwright/Chromium plus the CUGA browser extension"
      },
      {
        "id": "c",
        "text": "A PostgreSQL database"
      },
      {
        "id": "d",
        "text": "An E2B account"
      }
    ]
  },
  {
    "id": "q18",
    "difficulty": "medium",
    "question": "Which sequence best describes CUGA's journey as told in the talk?",
    "options": [
      {
        "id": "a",
        "text": "AppWorld -> WebArena -> UI automation -> Sovereign Core"
      },
      {
        "id": "b",
        "text": "UI automation -> WebArena (web) -> AppWorld (APIs) -> hybrid agent -> enterprise hardening"
      },
      {
        "id": "c",
        "text": "LangGraph fork -> Langflow plugin -> standalone agent"
      },
      {
        "id": "d",
        "text": "Enterprise product first, then open-sourced for benchmarks"
      }
    ]
  },
  {
    "id": "q19",
    "difficulty": "medium",
    "question": "According to the speaker, which models are CUGA's agents primarily tuned for, and why?",
    "options": [
      {
        "id": "a",
        "text": "Frontier models only, for maximum accuracy"
      },
      {
        "id": "b",
        "text": "Open-source models, because the primary target is sovereign deployment"
      },
      {
        "id": "c",
        "text": "Small on-device models, for mobile use"
      },
      {
        "id": "d",
        "text": "Only IBM Granite models"
      }
    ]
  },
  {
    "id": "q20",
    "difficulty": "medium",
    "question": "When configuring LLMs, what is CUGA's configuration priority (highest first)?",
    "options": [
      {
        "id": "a",
        "text": "TOML -> Environment variables -> Defaults"
      },
      {
        "id": "b",
        "text": "Defaults -> TOML -> Environment variables"
      },
      {
        "id": "c",
        "text": "Environment variables -> TOML -> Defaults"
      },
      {
        "id": "d",
        "text": "SDK only; env vars are ignored"
      }
    ]
  },
  {
    "id": "q21",
    "difficulty": "medium",
    "question": "What is the minimal SDK flow to run a CUGA agent in Python?",
    "options": [
      {
        "id": "a",
        "text": "agent = CugaAgent(tools=[...]); result = await agent.invoke(msg); result.answer"
      },
      {
        "id": "b",
        "text": "agent = Cuga.load('config.yaml'); agent.run_sync(msg)"
      },
      {
        "id": "c",
        "text": "graph = StateGraph(); graph.compile().run(msg)"
      },
      {
        "id": "d",
        "text": "cuga.chat(msg, tools=[...]).text"
      }
    ]
  },
  {
    "id": "q22",
    "difficulty": "medium",
    "question": "How does the SDK isolate state between different users' conversations?",
    "options": [
      {
        "id": "a",
        "text": "A separate CugaAgent process per user"
      },
      {
        "id": "b",
        "text": "Passing a thread_id per session"
      },
      {
        "id": "c",
        "text": "Separate .env files"
      },
      {
        "id": "d",
        "text": "It doesn't; state is global"
      }
    ]
  },
  {
    "id": "q23",
    "difficulty": "medium",
    "question": "Which IBM library does CUGA's knowledge engine use to parse and chunk PDFs, Office files, HTML, and images?",
    "options": [
      {
        "id": "a",
        "text": "Unstructured"
      },
      {
        "id": "b",
        "text": "Docling"
      },
      {
        "id": "c",
        "text": "Apache Tika"
      },
      {
        "id": "d",
        "text": "PyPDF2"
      }
    ]
  },
  {
    "id": "q24",
    "difficulty": "medium",
    "question": "A user uploads PTO documents that should only be visible within their current conversation. Which knowledge scope fits?",
    "options": [
      {
        "id": "a",
        "text": "agent"
      },
      {
        "id": "b",
        "text": "session"
      },
      {
        "id": "c",
        "text": "global"
      },
      {
        "id": "d",
        "text": "tenant"
      }
    ]
  },
  {
    "id": "q25",
    "difficulty": "medium",
    "question": "When is an Intent Guard evaluated during a run?",
    "options": [
      {
        "id": "a",
        "text": "After the final answer is composed"
      },
      {
        "id": "b",
        "text": "At the very first phase of the agent, stopping the request immediately if matched"
      },
      {
        "id": "c",
        "text": "Before each tool call"
      },
      {
        "id": "d",
        "text": "Only when a playbook is active"
      }
    ]
  },
  {
    "id": "q26",
    "difficulty": "medium",
    "question": "How does CUGA use agent skills (SKILL.md files) at runtime?",
    "options": [
      {
        "id": "a",
        "text": "All skill bodies are concatenated into the system prompt at startup"
      },
      {
        "id": "b",
        "text": "Short descriptions are listed in the prompt; the full body is pulled on demand via the load_skill tool"
      },
      {
        "id": "c",
        "text": "Skills are compiled into LangGraph nodes"
      },
      {
        "id": "d",
        "text": "Skills are only used by the supervisor"
      }
    ]
  },
  {
    "id": "q27",
    "difficulty": "medium",
    "question": "The demo agent had nine playbooks. Why are they triggered by natural-language similarity instead of all being injected into every prompt?",
    "options": [
      {
        "id": "a",
        "text": "Playbooks can only be read by the supervisor"
      },
      {
        "id": "b",
        "text": "Injecting only the playbook that passes the cosine-similarity threshold keeps the LLM focused, which matters especially for smaller models"
      },
      {
        "id": "c",
        "text": "Providers limit system prompts to one playbook"
      },
      {
        "id": "d",
        "text": "It is required for tool approval to work"
      }
    ]
  },
  {
    "id": "q28",
    "difficulty": "medium",
    "question": "How can a CugaSupervisor include an agent running on a remote server?",
    "options": [
      {
        "id": "a",
        "text": "Via the A2A (Agent-to-Agent) protocol as an external agent"
      },
      {
        "id": "b",
        "text": "Only by importing its Python module"
      },
      {
        "id": "c",
        "text": "Through a Langflow export"
      },
      {
        "id": "d",
        "text": "Remote agents are not supported"
      }
    ]
  },
  {
    "id": "q29",
    "difficulty": "medium",
    "question": "What does `cuga start manager` provide?",
    "options": [
      {
        "id": "a",
        "text": "A Kubernetes operator"
      },
      {
        "id": "b",
        "text": "A UI to edit tools, MCP servers, LLM, and policies as a draft, test in draft chat, then publish a versioned config"
      },
      {
        "id": "c",
        "text": "A CLI for managing API keys"
      },
      {
        "id": "d",
        "text": "A benchmark runner"
      }
    ]
  },
  {
    "id": "q30",
    "difficulty": "medium",
    "question": "Each app in the cuga-apps repository is structured as:",
    "options": [
      {
        "id": "a",
        "text": "A multi-service microservice deployment"
      },
      {
        "id": "b",
        "text": "A single-file FastAPI server wrapping one CugaAgent with a tool list and a system prompt"
      },
      {
        "id": "c",
        "text": "A Langflow JSON flow"
      },
      {
        "id": "d",
        "text": "A Jupyter notebook"
      }
    ]
  },
  {
    "id": "q31",
    "difficulty": "hard",
    "question": "The CUGA docs describe five architectural layers. Which ordering is correct?",
    "options": [
      {
        "id": "a",
        "text": "Clients -> Orchestrator -> Capabilities -> Persistence -> External services"
      },
      {
        "id": "b",
        "text": "Models -> Tools -> Policies -> Memory -> UI"
      },
      {
        "id": "c",
        "text": "Orchestrator -> Clients -> Persistence -> Capabilities -> External services"
      },
      {
        "id": "d",
        "text": "Planner -> Executor -> Reflector -> Finalizer -> Output"
      }
    ]
  },
  {
    "id": "q32",
    "difficulty": "hard",
    "question": "In a supervisor roster, a sub-agent declares only `mcp_servers: [crm]` and no `apps:`. Which tools does it receive?",
    "options": [
      {
        "id": "a",
        "text": "The entire tool registry"
      },
      {
        "id": "b",
        "text": "Only tools from the crm MCP server"
      },
      {
        "id": "c",
        "text": "No tools at all"
      },
      {
        "id": "d",
        "text": "Only LangChain tools"
      }
    ]
  },
  {
    "id": "q33",
    "difficulty": "hard",
    "question": "How are variables handled across sub-agents in CugaSupervisor?",
    "options": [
      {
        "id": "a",
        "text": "They are discarded after each delegation"
      },
      {
        "id": "b",
        "text": "They are aggregated into supervisor_variables with agent-name prefixes and can be passed to later agents, including over A2A when enabled"
      },
      {
        "id": "c",
        "text": "The last agent's variables overwrite earlier ones"
      },
      {
        "id": "d",
        "text": "Variables only exist within a single LLM call"
      }
    ]
  },
  {
    "id": "q34",
    "difficulty": "hard",
    "question": "Mechanically, how does CUGA enforce Tool Approval?",
    "options": [
      {
        "id": "a",
        "text": "By removing the tool from the tool list until approved"
      },
      {
        "id": "b",
        "text": "By injecting a hook at each tool call that can pause and ask the user"
      },
      {
        "id": "c",
        "text": "By asking the LLM to self-police"
      },
      {
        "id": "d",
        "text": "By routing all tool calls through Slack"
      }
    ]
  },
  {
    "id": "q35",
    "difficulty": "hard",
    "question": "How does CUGA store policies and retrieve the relevant ones?",
    "options": [
      {
        "id": "a",
        "text": "Hard-coded in the system prompt only"
      },
      {
        "id": "b",
        "text": "Policies are embedded for similarity retrieval; by default (storage mode 'local') vectors live in a SQLite file via sqlite-vec, while 'prod' mode uses PostgreSQL with pgvector"
      },
      {
        "id": "c",
        "text": "Redis only"
      },
      {
        "id": "d",
        "text": "As LangGraph checkpoints"
      }
    ]
  },
  {
    "id": "q36",
    "difficulty": "hard",
    "question": "Which statement about CUGA's RAG design is accurate per the talk?",
    "options": [
      {
        "id": "a",
        "text": "It stuffs all documents into every LLM call for maximum recall"
      },
      {
        "id": "b",
        "text": "It supports graph DBs out of the box"
      },
      {
        "id": "c",
        "text": "It pre-processes documents and offers a few preset pipeline configurations (e.g., speed vs. balanced) derived from experiments published at NeurIPS"
      },
      {
        "id": "d",
        "text": "It requires a frontier VLM to work"
      }
    ]
  },
  {
    "id": "q37",
    "difficulty": "hard",
    "question": "CUGA can improve over time through the optional Evolve integration. How does Evolve work?",
    "options": [
      {
        "id": "a",
        "text": "It fine-tunes the LLM's weights on successful runs"
      },
      {
        "id": "b",
        "text": "It analyzes run trajectories to generate guidelines, which are later injected into the prompt to mitigate errors and improve efficiency"
      },
      {
        "id": "c",
        "text": "It automatically rewrites playbooks after each run"
      },
      {
        "id": "d",
        "text": "It re-runs failed tasks until they succeed"
      }
    ]
  },
  {
    "id": "q38",
    "difficulty": "hard",
    "question": "How did the speaker distinguish an agent harness from a framework like LangGraph?",
    "options": [
      {
        "id": "a",
        "text": "LangGraph is closed source; harnesses are open"
      },
      {
        "id": "b",
        "text": "A framework doesn't prescribe the agent style (ReAct/CodeAct) or LLM, and you still build, run, and tune everything; a harness ships those decisions tuned, claimed to speed development roughly 10x"
      },
      {
        "id": "c",
        "text": "Harnesses don't support tools"
      },
      {
        "id": "d",
        "text": "There is no difference; the terms are synonyms"
      }
    ]
  },
  {
    "id": "q39",
    "difficulty": "hard",
    "question": "In the multi-agent travel planner example, how is the corporate travel policy applied to the compliance agent?",
    "options": [
      {
        "id": "a",
        "text": "As an Intent Guard on the supervisor"
      },
      {
        "id": "b",
        "text": "As a Playbook triggered by the word 'travel'"
      },
      {
        "id": "c",
        "text": "As a Tool Guide loaded into the compliance agent via add_tool_guide, with separate employee/manager/executive policy files"
      },
      {
        "id": "d",
        "text": "Hard-coded in the Slack approval tool"
      }
    ]
  },
  {
    "id": "q40",
    "difficulty": "hard",
    "question": "You want to publish a skill that teaches coding assistants (Claude Code, Cursor, Bob) how to author CUGA policies. Which repo is it meant for?",
    "options": [
      {
        "id": "a",
        "text": "cuga-skills"
      },
      {
        "id": "b",
        "text": "cuga-harness-kit"
      },
      {
        "id": "c",
        "text": "cuga-apps"
      },
      {
        "id": "d",
        "text": "cuga-agent/docs"
      }
    ]
  }
];
