// AUTO-GENERATED by scripts/build-quiz-data.mjs — do not hand edit.
// Do not commit the source pool file this was built from.

export interface QuizExplanation {
  explanation: string;
  source: string | null;
}

// Loaded via dynamic import() only when the results screen renders.
export const quizExplanations: Record<string, QuizExplanation> = {
  "q1": {
    "explanation": "CUGA is the ConfigUrable Generalist Agent, a generalist agent you configure for your domain rather than build from scratch.",
    "source": "cuga-agent README; docs.cuga.dev"
  },
  "q2": {
    "explanation": "CUGA is an open-source IBM Research project; issues and PRs are public on GitHub and outside contributors are welcome.",
    "source": "docs.cuga.dev; talk (AI Alliance, youtu.be/64WEB4S78nQ) 1:26-2:10"
  },
  "q3": {
    "explanation": "CUGA is an agent harness for the enterprise: you bring tools, policies, and knowledge; CUGA provides orchestration, planning, and governance.",
    "source": "cuga.dev; cuga-agent README"
  },
  "q4": {
    "explanation": "The harness handles the tedious infrastructure; the developer configures the domain aspects: tools, business rules and policies, when humans are interrupted, and skills.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 5:14-6:48, 51:33-52:28"
  },
  "q5": {
    "explanation": "AppWorld has 750 real-world tasks spanning 457 APIs. CUGA was #1 from 07/25 to 02/26; the speaker noted it is now around #2.",
    "source": "cuga-agent README; talk (AI Alliance, youtu.be/64WEB4S78nQ) 7:38-8:00"
  },
  "q6": {
    "explanation": "WebArena tests autonomous web agents; CUGA was #1 there for roughly six months.",
    "source": "cuga-agent README; talk (AI Alliance, youtu.be/64WEB4S78nQ) 7:16-7:32"
  },
  "q7": {
    "explanation": "Policies can be authored with the Python SDK (e.g., agent.policies.add_intent_guard) or in the web UI, as shown live in the talk.",
    "source": "cuga-agent README (Policy System); talk (AI Alliance, youtu.be/64WEB4S78nQ) 18:28-18:43"
  },
  "q8": {
    "explanation": "OpenAPI and MCP tools are configured in mcp_servers.yaml; LangChain tools (Python functions) are passed to CugaAgent(tools=[...]).",
    "source": "cuga-agent README (Adding Tools); talk (AI Alliance, youtu.be/64WEB4S78nQ) 8:25-8:49"
  },
  "q9": {
    "explanation": "IBM Research hosts live demos on Hugging Face Spaces: ibm-research/cuga-agent and ibm-research/cuga-apps.",
    "source": "cuga-agent README (Try CUGA Live badge); cuga-apps README (Try it live)"
  },
  "q10": {
    "explanation": "`cuga viz` opens a dashboard for analyzing trajectories, decisions, and tool usage.",
    "source": "cuga-agent README (Quick Start)"
  },
  "q11": {
    "explanation": "Five: Playbook, Intent Guard, Tool Guide, Tool Approval, and Output Formatter.",
    "source": "cuga-agent README; talk (AI Alliance, youtu.be/64WEB4S78nQ) 15:26-17:02"
  },
  "q12": {
    "explanation": "There is no Rate Limiter policy. Tool-call budgets exist as [advanced_features] settings, not a policy type.",
    "source": "cuga-agent README"
  },
  "q13": {
    "explanation": "Tool Approval pauses execution and asks the user to approve or deny the call, as shown in the demo with the member-claims tool.",
    "source": "cuga-agent README; talk (AI Alliance, youtu.be/64WEB4S78nQ) 29:16-30:18"
  },
  "q14": {
    "explanation": "Output Formatters shape the final response based on triggers. In the demo the consumer was another agent, so claims were returned as JSON.",
    "source": "cuga-agent README (policy list); talk (AI Alliance, youtu.be/64WEB4S78nQ) 30:35-31:31"
  },
  "q15": {
    "explanation": "Intent Guards block (or modify) matching intents; higher-priority guards are checked first.",
    "source": "cuga-agent README (SDK Quick Start)"
  },
  "q16": {
    "explanation": "Playbooks are SOPs, e.g. 'retrieve and approve claims': which tools to call, in what order, and how to answer.",
    "source": "cuga-agent README; talk (AI Alliance, youtu.be/64WEB4S78nQ) 15:26-15:54, 24:29-25:15"
  },
  "q17": {
    "explanation": "Hybrid mode combines API and web actions; it needs `playwright install chromium` and the browser extension side panel.",
    "source": "cuga-agent README (Hybrid Task Execution; Task Modes)"
  },
  "q18": {
    "explanation": "The team started in UI-based LLM automation, went benchmark-driven on WebArena and then AppWorld, merged into a web/API/hybrid agent, then hardened it with customers.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 6:54-8:25"
  },
  "q19": {
    "explanation": "The goal is for CUGA, properly configured, to behave on open models similarly to a frontier model, which suits sovereign/air-gapped environments.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 13:50-14:21; Hugging Face blog (CUGA on Hugging Face)"
  },
  "q20": {
    "explanation": "Environment variables override TOML, which overrides built-in defaults; e.g. MODEL_NAME overrides settings.<provider>.toml.",
    "source": "cuga-agent README (LLM Configuration)"
  },
  "q21": {
    "explanation": "Construct CugaAgent with tools, `await agent.invoke(...)`, and read `result.answer`; `agent.stream()` streams execution.",
    "source": "cuga-agent README (Using CUGA as a Python SDK)"
  },
  "q22": {
    "explanation": "thread_id isolates per-user sessions and also scopes session-level knowledge.",
    "source": "cuga-agent README (SDK Key Features; Session-Scoped Knowledge)"
  },
  "q23": {
    "explanation": "Docling parses and chunks documents; they are then embedded into a vector store, and answers come back with source citations.",
    "source": "cuga-agent README (Knowledge Base); talk (AI Alliance, youtu.be/64WEB4S78nQ) 34:35-35:18"
  },
  "q24": {
    "explanation": "Session scope is per-thread and isolated; agent scope is permanent and shared. The agent can search both in one query, as the demo showed.",
    "source": "cuga-agent README (Session-Scoped Knowledge); talk (AI Alliance, youtu.be/64WEB4S78nQ) 33:07-34:18, 41:05-41:50"
  },
  "q25": {
    "explanation": "Intent Guards fire up front. In the demo a guard blocked sports questions so the healthcare agent stayed on topic.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 15:54-16:13, 26:44-28:26"
  },
  "q26": {
    "explanation": "Progressive disclosure keeps prompts small; the model calls load_skill when a task matches a skill.",
    "source": "cuga-agent README (Agent skills)"
  },
  "q27": {
    "explanation": "Nine playbooks of ~20 lines each would flood the context. A frontier model might cope, but smaller models struggle, so only the matching SOP is injected.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 24:56-26:06"
  },
  "q28": {
    "explanation": "External agents follow A2A and expose an agent card (and security tokens if needed); the supervisor uses the card's description and capabilities.",
    "source": "cuga-agent README (CugaSupervisor); design.md; talk (AI Alliance, youtu.be/64WEB4S78nQ) 44:18-44:46"
  },
  "q29": {
    "explanation": "Manage mode separates draft from production; published versions are tracked for audit and roll-forward.",
    "source": "cuga-agent README (Manage, publish, and self-hosting); talk (AI Alliance, youtu.be/64WEB4S78nQ) 23:37-23:50"
  },
  "q30": {
    "explanation": "The developer's part shrinks to a tool list plus a system prompt; the right panel shows live state the agent pushes.",
    "source": "cuga-apps README; talk (AI Alliance, youtu.be/64WEB4S78nQ) 1:00:39-1:00:50"
  },
  "q31": {
    "explanation": "Clients (SDK, server, UI) sit on top; the orchestrator and capabilities run behind them, backed by persistence and external services.",
    "source": "docs.cuga.dev (Quick Start / How CUGA works)"
  },
  "q32": {
    "explanation": "mcp_servers: entries now count as named apps. Only an agent that lists neither apps: nor mcp_servers: receives everything.",
    "source": "cuga-agent README (CugaSupervisor, IMPORTANT note)"
  },
  "q33": {
    "explanation": "Session-wide variable propagation is extended across agents; names are prefixed to avoid collisions, and pass_variables_a2a extends this to remote agents.",
    "source": "design.md (Variable Management); cuga-agent README (Supervisor features); talk (AI Alliance, youtu.be/64WEB4S78nQ) 43:28-43:54"
  },
  "q34": {
    "explanation": "A hook sits in the tool-calling path; when the selected tool matches an approval policy, execution pauses for human confirmation.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 30:18-30:35"
  },
  "q35": {
    "explanation": "[storage].mode defaults to 'local' (sqlite-vec in DBS_DIR/cuga.db) and switches to PostgreSQL + pgvector with mode = 'prod'. Note: the talk says SQLite 'in memory', but the default store is a local file.",
    "source": "src/cuga/settings.toml ([storage] section); release notes (PostgreSQL + pgvector); talk (AI Alliance, youtu.be/64WEB4S78nQ) 18:52-19:38"
  },
  "q36": {
    "explanation": "Stuffing context is costly and slow, so CUGA pre-processes documents and distills its many pipeline options into four presets. Graph DBs are not supported out of the box.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 32:12-33:07, 36:17-37:19"
  },
  "q37": {
    "explanation": "Evolve closes a learning loop: it analyzes trajectories from completed runs, derives guidelines from what went well and what failed, and injects relevant guidelines into later prompts.",
    "source": "cuga-agent README (Optional: Use Evolve with CUGA); talk (AI Alliance, youtu.be/64WEB4S78nQ) 11:13-11:36"
  },
  "q38": {
    "explanation": "A framework is a developer toolkit; a harness is everything needed from framework to enterprise-grade deployment, including guardrails, sandboxing, and observability.",
    "source": "talk (AI Alliance, youtu.be/64WEB4S78nQ) 53:58-56:14"
  },
  "q39": {
    "explanation": "The compliance agent loads .cuga/tool_guides/policy_employee.md via add_tool_guide; manager and executive variants exist, matching the talk's per-role policy.",
    "source": "docs/examples/travel_agent/README.md; talk (AI Alliance, youtu.be/64WEB4S78nQ) 49:45-49:52"
  },
  "q40": {
    "explanation": "cuga-skills holds end-user productivity skills installed into .cuga/skills; skills for building CUGA agents (tools, policies, trajectories) belong in cuga-harness-kit.",
    "source": "cuga-skills README; cuga-harness-kit README"
  }
};
